// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGM.Data;

#nullable disable

namespace SGM.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20250306184438_Observacion")]
    partial class Observacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SGM.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("SGM.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amp")
                        .HasColumnType("REAL");

                    b.Property<int>("Bpm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmwareVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grabador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumSerieGrabador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumSerieSimulador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Simulador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftAnalisis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Observacion");
                });

            modelBuilder.Entity("SGM.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrdenTrabajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Trabajo");
                });

            modelBuilder.Entity("SGM.Models.Trabajo", b =>
                {
                    b.HasOne("SGM.Models.Modelo", "Modelo")
                        .WithMany("Trabajos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("SGM.Models.Modelo", b =>
                {
                    b.Navigation("Trabajos");
                });
#pragma warning restore 612, 618
        }
    }
}
