// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGM.Data;

#nullable disable

namespace SGM.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SGM.Models.ControlEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resonsable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("ControlEquipo");
                });

            modelBuilder.Entity("SGM.Models.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadRestante")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId");

                    b.ToTable("Entrega");
                });

            modelBuilder.Entity("SGM.Models.InsumoCritico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InsumoCritico");
                });

            modelBuilder.Entity("SGM.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("SGM.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirmwareVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grabador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumSerieGrabador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumSerieSimulador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Simulador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftAnalisis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Observacion");
                });

            modelBuilder.Entity("SGM.Models.Produccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrdenProduccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("TrabajoId");

                    b.ToTable("Produccion");
                });

            modelBuilder.Entity("SGM.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrdenTrabajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Trabajo");
                });

            modelBuilder.Entity("SGM.Models.ControlEquipo", b =>
                {
                    b.HasOne("SGM.Models.Modelo", "Modelo")
                        .WithMany("ControlEquipos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("SGM.Models.Entrega", b =>
                {
                    b.HasOne("SGM.Models.Trabajo", "OrdenTrabajo")
                        .WithMany("Entregas")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("SGM.Models.Produccion", b =>
                {
                    b.HasOne("SGM.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGM.Models.Trabajo", "Trabajo")
                        .WithMany("Producciones")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("SGM.Models.Trabajo", b =>
                {
                    b.HasOne("SGM.Models.Modelo", "Modelo")
                        .WithMany("Trabajos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("SGM.Models.Modelo", b =>
                {
                    b.Navigation("ControlEquipos");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("SGM.Models.Trabajo", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Producciones");
                });
#pragma warning restore 612, 618
        }
    }
}
